### PR TITLE
My enumerable

### PR DESCRIPTION
**Pull request by iankiema**
The following files have been added 
-Linter files
-My_enumerable.rb
-My list.rb
-Test_solution.rb files
-Readme files

### CODE REVIEW

**Review by 1GORDON — COMMENTED** [review]
##
## Hi @iankiema, and @ngalamac ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Kindly ensure your linter checks are passing and are in green. Currently, your linter checks are failing the tests. 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by shella12 — COMMENTED** [review]
Hi @iankiema and @ngalamac, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow. Please make sure to create a PR from feature branch to  `dev` branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ngalamac** [comment]
Hi @shella12 

Thank you so much for the feedback.
Please I think from the project requirements we are to use GitHub flow , not GitFlow.
This therefore requires a pull request to made from a feature branch to the main branch.

pr

Thank you for your kind attention

**Review by afanimartin — APPROVED** [review]
Hi @iankiema, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- `MyList` and `MyEnumerable` are saved in two separate files.
- `MyList` class has an instance variable `@list`.
- `MyList` class has the `#initialize` method that accepts multiple arguments.
- `MyList` class implements `#each` method that yields all members of `@list` as expected

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
